### ISSUE TITLE
Search Traveler box - Dropdown items are looking like disabled.

### ISSUE THREAD

**Issue by abhilekh10** [nxtComponent/ComponentsWeb#11]
![image](https://user-images.githubusercontent.com/24823813/30686837-136b117a-9ed7-11e7-9856-fc68efc85dce.png)

**Comment by tavisca-dpingale** [comment]
Fixed..

https://github.com/nxtComponent/t-hotel-search/pull/4

**Comment by garats** [comment]
@abhilekh10 
This is fixed. Please confirm and close it.
