### ISSUE TITLE
Results -> The spacing between Text (we found X hotels) and filter tags is not according to VD

### ISSUE THREAD

**Issue by abhilekh10** [nxtComponent/ComponentsWeb#14]
Results -> The spacing between Text (we found X hotels) and filter tags is not according to VD

![image](https://user-images.githubusercontent.com/24823813/30687086-e2621a46-9ed7-11e7-8f34-27d62a5d53ad.png)

**Comment by tavisca-dpingale** [comment]
Fixed ...

https://github.com/nxtComponent/t-tags-input/pull/2

**Comment by garats** [comment]
@abhilekh10 
This is fixed. Please confirm and close it.
