### ISSUE TITLE
Hotel Results - Filters are not working as expected. Check behavior in screenshot.

### ISSUE THREAD

**Issue by abhilekh10** [nxtComponent/ComponentsWeb#19]
Issues in filtering results

![image](https://user-images.githubusercontent.com/24823813/30730010-53f61a64-9f81-11e7-8850-6392d45c5b17.png)

**Comment by ppparihar** [comment]
@abhilekh10  it is fixed now. you can close it after verified from your side.

**Comment by abhilekh10** [comment]
The behavior mentioned in above screenshot is not resolved.
