### ISSUE TITLE
Hotel Results ->In case of no deals->Only deals tags are coming up

### ISSUE THREAD

**Issue by abhilekh10** [nxtComponent/ComponentsWeb#21]
Hotel Results ->In case of no deals->Only deals tags are coming up

![image](https://user-images.githubusercontent.com/24823813/30730136-62b74dce-9f82-11e7-8c29-1088b52441f4.png)

**Comment by ppparihar** [comment]
@abhilekh10  It has been fixed. Please close it after verified from your side.

**Comment by abhilekh10** [comment]
Working now.
