### ISSUE TITLE
Mozilla search widget - alignement of fields / spacing between them / the search button size is distorted

### ISSUE THREAD

**Issue by abhilekh10** [nxtComponent/ComponentsWeb#27]
![image](https://user-images.githubusercontent.com/24823813/30897654-05ca162c-a375-11e7-87b6-84dcc1520a5d.png)

**Comment by tavisca-dpingale** [comment]
Fixed..
![27-fixed](https://user-images.githubusercontent.com/15605278/31655696-50a46a3a-b347-11e7-85e6-4db9a801b359.jpg)

**Comment by garats** [comment]
@abhilekh10 
This is fixed. Please confirm and close it.
