### ISSUE TITLE
Mozilla->Hotel Results ->Alignment of button "See available rooms" is broken

### ISSUE THREAD

**Issue by abhilekh10** [nxtComponent/ComponentsWeb#29]
![image](https://user-images.githubusercontent.com/24823813/30897880-484ac626-a376-11e7-9f33-fec2b76b08f8.png)

**Comment by tavisca-dpingale** [comment]
Fixed in t-hotel-item component
https://github.com/nxtComponent/t-hotel-item/pull/1

**Comment by garats** [comment]
@abhilekh10 
This is fixed. Please confirm and close it.
