### ISSUE TITLE
Mobile->Alignment broken in mobile/Andriod/Chrome

### ISSUE THREAD

**Issue by abhilekh10** [nxtComponent/ComponentsWeb#46]
![screenshot_20171025-143533](https://user-images.githubusercontent.com/24823813/31990219-1222b7ca-b992-11e7-8e55-77cd9a038523.png)

**Comment by tavisca-dpingale** [comment]
@abhilekh10 Fixed broken phone number

https://github.com/nxtComponent/t-header/pull/2

**Comment by tavisca-dpingale** [comment]
@abhilekh10 @ppparihar 
The same changes are also done in travelnxt t-header component

https://github.com/travelnxtComponents/t-header/pull/2
