### ISSUE TITLE
Mobile: Autosuggest is not taking full screen. Check VD for reference

### ISSUE THREAD

**Issue by abhilekh10** [nxtComponent/ComponentsWeb#48]
Mobile: Autosuggest is not taking full screen. Check VD for reference

Check this url of vd - https://projects.invisionapp.com/share/6E9PJ7R4Q#/screens/212359126

Should behave like this : 

![image](https://user-images.githubusercontent.com/24823813/31991630-d69e7aaa-b995-11e7-87f0-718831356cdc.png)

**Comment by tavisca-dpingale** [comment]
@abhilekh10  Fixed

https://github.com/nxtComponent/t-hotel-search/pull/6
