### ISSUE TITLE
Multiple change on hotel results

### ISSUE THREAD

**Issue by abhilekh10** [nxtComponent/ComponentsWeb#60]
1. Area info - change weight 500 to 400
2. Align "see room" with "Aminties"
3. Add Map and city center infor with Area
4. Remove decimals from price
5. Traveler pop alignment
6. Add advertisement image on listing

Design link - https://projects.invisionapp.com/share/6E9PJ7R4Q#/screens/212359126

**Comment by SunilSalve24** [comment]
Changes are done
